# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gcdist1 <- function(lon, lat, eps) {
    .Call(`_smerc_gcdist1`, lon, lat, eps)
}

gcdist2 <- function(lon1, lat1, lon2, lat2, eps) {
    .Call(`_smerc_gcdist2`, lon1, lat1, lon2, lat2, eps)
}

eucdist1 <- function(x, y, eps) {
    .Call(`_smerc_eucdist1`, x, y, eps)
}

eucdist2 <- function(x1, y1, x2, y2, eps) {
    .Call(`_smerc_eucdist2`, x1, y1, x2, y2, eps)
}

subv_int <- function(v, idx) {
    .Call(`_smerc_subv_int`, v, idx)
}

does_intersect_vi <- function(x, y) {
    .Call(`_smerc_does_intersect_vi`, x, y)
}

noc_cpp <- function(x) {
    .Call(`_smerc_noc_cpp`, x)
}

stat_poisson_adj_cpp <- function(yin, ty, logein, logeout, a, pen, min_cases, return_max) {
    .Call(`_smerc_stat_poisson_adj_cpp`, yin, ty, logein, logeout, a, pen, min_cases, return_max)
}

stat_binom_adj_cpp <- function(yin, ty, popin, popout, logpopin, logpopout, tpop, min_cases, return_max) {
    .Call(`_smerc_stat_binom_adj_cpp`, yin, ty, popin, popout, logpopin, logpopout, tpop, min_cases, return_max)
}

scsg2_cpp <- function(nn, w, idx, nlevel, lprimes, verbose = FALSE) {
    .Call(`_smerc_scsg2_cpp`, nn, w, idx, nlevel, lprimes, verbose)
}

stat_poisson_cpp <- function(yin, yout, ein, eout, a, shape) {
    .Call(`_smerc_stat_poisson_cpp`, yin, yout, ein, eout, a, shape)
}

stat_poisson0_cpp <- function(yin, yout, ein, eout) {
    .Call(`_smerc_stat_poisson0_cpp`, yin, yout, ein, eout)
}

stat_binom_cpp <- function(yin, yout, ty, popin, popout, tpop) {
    .Call(`_smerc_stat_binom_cpp`, yin, yout, ty, popin, popout, tpop)
}

mc_pvalue_cpp <- function(tobs, tsim) {
    .Call(`_smerc_mc_pvalue_cpp`, tobs, tsim)
}

flex_test_cpp <- function(nn, cases, pop, w, k, ex, type, nsim, alpha, lprimes, verbose = TRUE) {
    .Call(`_smerc_flex_test_cpp`, nn, cases, pop, w, k, ex, type, nsim, alpha, lprimes, verbose)
}

