# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scsg2_cpp <- function(nn, w, idx, nlevel, lprimes, verbose = FALSE) {
    .Call('_smerc_scsg2_cpp', PACKAGE = 'smerc', nn, w, idx, nlevel, lprimes, verbose)
}

